---

- name: Installation of nginx Ingress Controller
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/baremetal/deploy.yaml

- name: Configure the nginx Ingress Controller as the default one
  ansible.builtin.command: kubectl annotate ingressclass nginx ingressclass.kubernetes.io/is-default-class=true

- name: Pause for installation of Ingress Controller
  ansible.builtin.pause:
    seconds: 60
